baseURL: https://yakoxff.pages.dev/
timeZone: Asia/Shanghai
hasCJKLanguage: true
defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

# 明确指定布局目录
layoutDir: layouts
# 确保短代码路径正确
shortcodeDir: layouts/_shortcodes

outputs:
  home:
    - HTML
    - RSS
    - Sitemap


# 安全设置，允许内联短代码
security:
  enableInlineShortcodes: true

# 排除以下划线开头的 Markdown 文件
exclude:
  - "**/_*.md"
  - "**/_*.markdown"
  - "content/fictions/草台班子/_大纲.md"
