author: Eltrac
email: hi@guhub.cn
mainSections:
  - posts
  - fictions
  - library
favicon: /favicon.png
externalJSFIles:
  - /js/littlefoot.js
footerExternalLinks:
  - name: GitHub
    link: https://github.com/BigCoke233/geek-death-project
    icon: https://image.guhub.cn/uPic/2025/01/NqL5b5.png
  - name: Travelling
    link: https://www.travellings.cn/go.html
    icon: https://www.travellings.cn/assets/favicon.png
  - name: Telegram Channel
    link: https://t.me/geedeapro
    icon: /img/telegram.svg
giscus:
  repo: BigCoke233/geek-death-project
  repoId: R_kgDONPoyVw
  category: General
  categoryId: DIC_kwDONPoyV84Clumc
  mapping: og:title
  strict: 1
  reactionsEnabled: 0
  emitMetadata: 0
  inputPosition: top
  theme: "https://www.geedea.pro/css/giscus_noborder.css"
