nav:
  - name: 长文
    link: /posts/
    target: _self
  - name: 摘录
    link: /cards/
    target: _self
  - name: 阅读
    link: /library/
    target: _self
  # - name: 虚构
  #   link: /fictions/
  #   target: _self
  - name: 关于
    link: /about/
    target: _self
footerInternalLinks:
  - name: 侠客
    link: /xiake/
  - name: 标记
    link: /highlights/
  - name: 设置
    link: /settings/
  # - name: 赞助
  #   link: /sponsor/
