author: Yak0xff
email: hi@guhub.cn
description: "Yak0xff 的个人博客 - 分享技术、思考与生活"
twitter: zh_robin
author_twitter: zh_robin
favicon: /favicon.ico
# 默认的社交媒体分享图片
default_og_image: /img/header.png
mainSections:
  - posts
  - fictions
  - library
favicon: /favicon.png
externalJSFIles:
  - /js/littlefoot.js
footerExternalLinks:
  - name: GitHub
    link: https://github.com/Yak0xff/yakoxff.github.io
    icon: /img/github.png
  - name: Travelling
    link: https://www.travellings.cn/go.html
    icon: https://www.travellings.cn/assets/favicon.png
  - name: X
    link: https://x.com/zh_robin
    icon: /img/x.png
giscus:
  repo: Yak0xff/yakoxff.github.io
  repoId: R_kgDOPv9iUg
  category: General
  categoryId: DIC_kwDOPv9iUs4Cvcyk
  mapping: og:title
  strict: 1
  reactionsEnabled: 0
  emitMetadata: 0
  inputPosition: top
  theme: "https://yakoxff.pages.dev/css/giscus_noborder.css"
